name: GOGO Shop On-premise stage CD Workflow

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Gradle's permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

  deploy:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass and OpenSSH
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass openssh-client

      - name: SSH Command to Deploy using Bastion and Target Instance
        run: |
          sshpass -p "${{ secrets.STAGE_ON_PREMISE_PASSWORD }}" ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.STAGE_ON_PREMISE_HOST }} << 'EOF'
              mkdir -p /home/ubuntu/gogo-shop
              cd /home/ubuntu/gogo-shop

              if [ ! -d ".git" ]; then
                git clone -b master https://github.com/team-gogo/gogo-shop.git .
              else
                git pull origin master
              fi

              ./gradlew clean build

              docker build -f DockerFileProd -t gogo-shop-prod .

              docker stop gogo-shop-prod || true
              docker rm gogo-shop-prod || true

              docker run -d -p 8084:8084 --add-host host.docker.internal:host-gateway --name gogo-shop-prod gogo-shop-prod

      - name: SSH Success Notification
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0x4CAF50
          title: "배포 성공"
          message: "GOGO Shop On-premise stage deployment completed successfully."

      - name: SSH Failure Notification
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          color: 0xFF4C4C
          title: "배포 실패"
          message: "GOGO Shop On-premise stage deployment failed. Check the logs for details."